### PR TITLE
Dependencies refresh

### PR DESCRIPTION
**Pull request by viktor44**
It's a first part of `electron-process-manager` fixing.
Updated dependencies that are used in the library

### CODE REVIEW

**Comment by viktor44** [comment]
Could you publish a new version please?

**Comment by magne4000** [comment]
I do not have access to this package, it's not published under `@getstation`. You will need to create a fork

**Comment by viktor44** [comment]
> I do not have access to this package, it's not published under `@getstation`. You will need to create a fork

I'm not sure I got it right.
Should we just change the name in `package.json` to `"name": "@getstation/electron-process-reporter"`?

**Comment by viktor44** [comment]
What's about `electron-process-manager`? Can you publish it?

**Comment by magne4000** [comment]
> > I do not have access to this package, it's not published under `@getstation`. You will need to create a fork
> 
> I'm not sure I got it right. Should we just change the name in `package.json` to `"name": "@getstation/electron-process-reporter"`?

Yes 👍 


> What's about `electron-process-manager`? Can you publish it?

This one I have the rights to publish it

**Pull request merged**
